services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 4000:4000
    command: mix phx.server
    volumes:
      - .:/app

volumes:
  db_volume:
